// ─── Social App Design Tokens ─────────────────────────────────────────────────
const tokens = {
  // Brand (purple/violet – social & modern)
  brand:        "#6C63FF",
  brandDark:    "#554ECC",
  brandLight:   "#EEF0FF",
  brandGlow:    "rgba(108,99,255,0.20)",
  // Gradients
  gradientAuth: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
  gradientBrand:"linear-gradient(135deg, #6C63FF 0%, #a78bfa 100%)",
  gradientCover:"linear-gradient(135deg, #6C63FF 0%, #EC4899 100%)",
  gradientStat1:"linear-gradient(135deg, #6C63FF 0%, #a78bfa 100%)",
  gradientStat2:"linear-gradient(135deg, #EC4899 0%, #f87171 100%)",
  gradientStat3:"linear-gradient(135deg, #06b6d4 0%, #22d3ee 100%)",
  gradientStat4:"linear-gradient(135deg, #10b981 0%, #34d399 100%)",
  // Text
  textPrimary:  "#111827",
  textSecondary:"#6B7280",
  textMuted:    "#9CA3AF",
  // Surfaces
  bgPage:       "#F3F4F8",
  bgCard:       "#FFFFFF",
  bgHover:      "#F9FAFB",
  // Borders & shadows
  border:       "#E5E7EB",
  shadow:       "0 2px 12px rgba(0,0,0,0.08)",
  shadowMd:     "0 4px 20px rgba(0,0,0,0.10)",
  shadowLg:     "0 8px 40px rgba(0,0,0,0.14)",
  // Radius
  radius:       "14px",
  radiusSm:     "8px",
  radiusXs:     "6px",
  // Status
  error:        "#EF4444",
  success:      "#10B981",
  // Sidebar
  sidebar:      "#111827",
};

// ─── Shared Styles ─────────────────────────────────────────────────────────────
const styles = {
  // ── Auth layout ──
  authPage: {
    display: "flex",
    minHeight: "100vh",
    background: tokens.gradientAuth,
  },
  authLeft: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "60px 52px",
    color: "#fff",
    position: "relative",
    overflow: "hidden",
  },
  authBrand: {
    fontSize: "42px",
    fontWeight: "800",
    letterSpacing: "-1.5px",
    color: "#fff",
    marginBottom: "12px",
  },
  authTagline: {
    fontSize: "16px",
    color: "rgba(255,255,255,0.60)",
    maxWidth: "320px",
    lineHeight: "1.65",
    fontWeight: "400",
    marginBottom: "36px",
  },
  authBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 18px",
    borderRadius: "50px",
    background: "rgba(255,255,255,0.10)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.18)",
    color: "#a78bfa",
    fontSize: "13px",
    fontWeight: "600",
    letterSpacing: "0.3px",
  },
  authRight: {
    width: "480px",
    minWidth: "380px",
    background: tokens.bgCard,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "60px 52px",
    overflowY: "auto",
  },

  // ── Card (generic) ──
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    background: tokens.gradientAuth,
  },
  center: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    background: tokens.bgPage,
  },
  card: {
    backgroundColor: tokens.bgCard,
    padding: "36px 40px",
    borderRadius: tokens.radius,
    width: "90%",
    maxWidth: "440px",
    boxShadow: tokens.shadowLg,
    textAlign: "center",
  },

  // ── Form headings ──
  title: {
    fontSize: "26px",
    fontWeight: "800",
    color: tokens.textPrimary,
    letterSpacing: "-0.5px",
    marginBottom: "6px",
    lineHeight: 1.2,
  },
  subtitle: {
    fontSize: "14px",
    color: tokens.textSecondary,
    marginBottom: "28px",
  },

  // ── Inputs ──
  inputWrap: {
    width: "100%",
    marginBottom: "4px",
  },
  inputLabel: {
    display: "block",
    fontSize: "12px",
    fontWeight: "600",
    color: tokens.textSecondary,
    textTransform: "uppercase",
    letterSpacing: "0.6px",
    marginBottom: "6px",
    textAlign: "left",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: tokens.radiusSm,
    border: `1.5px solid ${tokens.border}`,
    fontSize: "14px",
    fontWeight: "500",
    color: tokens.textPrimary,
    background: "#FAFAFA",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.18s, box-shadow 0.18s",
    fontFamily: "inherit",
  },
  textarea: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: tokens.radiusSm,
    border: `1.5px solid ${tokens.border}`,
    fontSize: "14px",
    fontWeight: "500",
    color: tokens.textPrimary,
    background: "#FAFAFA",
    outline: "none",
    boxSizing: "border-box",
    resize: "vertical",
    minHeight: "80px",
    lineHeight: "1.5",
    fontFamily: "inherit",
    transition: "border-color 0.18s",
  },

  // ── Buttons ──
  button: {
    width: "100%",
    padding: "13px",
    marginTop: "8px",
    border: "none",
    borderRadius: tokens.radiusSm,
    background: tokens.gradientBrand,
    color: "#fff",
    fontWeight: "700",
    fontSize: "15px",
    cursor: "pointer",
    letterSpacing: "0.2px",
    boxShadow: `0 4px 15px ${tokens.brandGlow}`,
    transition: "opacity 0.18s, transform 0.1s",
    fontFamily: "inherit",
  },
  buttonOutline: {
    width: "100%",
    padding: "12px",
    border: `1.5px solid ${tokens.border}`,
    borderRadius: tokens.radiusSm,
    background: "#fff",
    color: tokens.textPrimary,
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    fontFamily: "inherit",
    transition: "background 0.15s",
  },

  // ── Link ──
  link: {
    marginTop: "18px",
    color: tokens.brand,
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    display: "block",
    textAlign: "center",
  },

  // ── Form ──
  form: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "12px",
  },
  signupGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "0 14px",
  },

  // ── Messages ──
  error: {
    color: tokens.error,
    fontSize: "12px",
    fontWeight: "500",
    textAlign: "left",
    marginTop: "3px",
  },
  errorBanner: {
    background: "#FFF5F5",
    border: `1.5px solid #FECACA`,
    borderRadius: tokens.radiusSm,
    padding: "10px 14px",
    color: tokens.error,
    fontSize: "13px",
    fontWeight: "500",
    marginBottom: "14px",
  },
  success: {
    background: "#ECFDF5",
    border: `1.5px solid #A7F3D0`,
    borderRadius: tokens.radiusSm,
    padding: "10px 14px",
    color: tokens.success,
    fontSize: "13px",
    fontWeight: "600",
    marginBottom: "14px",
  },

  // ── Divider ──
  divider: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    margin: "18px 0",
    color: tokens.textMuted,
    fontSize: "12px",
    fontWeight: "600",
    letterSpacing: "0.5px",
  },
  dividerLine: {
    flex: 1,
    height: "1px",
    background: tokens.border,
  },

  // ── Dashboard / Social ──
  dashPage: {
    display: "flex",
    minHeight: "100vh",
    background: tokens.bgPage,
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif",
  },
  sidebar: {
    width: "220px",
    minWidth: "220px",
    background: tokens.sidebar,
    display: "flex",
    flexDirection: "column",
    padding: "0 0 24px 0",
    position: "sticky",
    top: 0,
    height: "100vh",
  },
  sidebarLogo: {
    padding: "24px 20px 18px",
    fontSize: "22px",
    fontWeight: "800",
    color: "#fff",
    letterSpacing: "-0.5px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    marginBottom: "8px",
  },
  sidebarLogoAccent: {
    color: "#a78bfa",
  },
  sidebarItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "11px 20px",
    color: "rgba(255,255,255,0.55)",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    borderLeft: "3px solid transparent",
    transition: "all 0.15s",
    userSelect: "none",
  },
  sidebarItemActive: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "11px 20px",
    color: "#fff",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "700",
    background: "rgba(108,99,255,0.18)",
    borderLeft: `3px solid ${tokens.brand}`,
    userSelect: "none",
  },
  sidebarDivider: {
    height: "1px",
    background: "rgba(255,255,255,0.08)",
    margin: "10px 0",
  },
  sidebarBottom: {
    marginTop: "auto",
    padding: "0 12px",
  },
  logoutButton: {
    width: "100%",
    padding: "10px 14px",
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: tokens.radiusSm,
    background: "transparent",
    color: "rgba(255,255,255,0.65)",
    fontWeight: "600",
    fontSize: "13px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    fontFamily: "inherit",
  },
  dashMain: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  },
  dashTopbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 28px",
    background: tokens.bgCard,
    borderBottom: `1px solid ${tokens.border}`,
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  dashTopbarTitle: {
    fontSize: "18px",
    fontWeight: "800",
    color: tokens.textPrimary,
    letterSpacing: "-0.3px",
  },
  dashTopbarRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  avatarCircle: {
    width: "38px",
    height: "38px",
    borderRadius: "50%",
    background: tokens.gradientBrand,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontWeight: "800",
    fontSize: "14px",
    flexShrink: 0,
    cursor: "pointer",
  },
  avatarCircleLg: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    background: tokens.gradientBrand,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontWeight: "800",
    fontSize: "28px",
    flexShrink: 0,
    border: "4px solid #fff",
    boxShadow: tokens.shadowMd,
  },
  dashContent: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 28px",
  },
  infoCard: {
    background: tokens.bgCard,
    borderRadius: tokens.radius,
    padding: "22px",
    boxShadow: tokens.shadow,
    border: `1px solid ${tokens.border}`,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "4px 10px",
    borderRadius: "50px",
    fontSize: "11px",
    fontWeight: "700",
    background: tokens.brandLight,
    color: tokens.brand,
  },
};

export { tokens };
export default styles;
